esphome:
  friendly_name: $room Dial
  on_boot:
    then:
      # read the RTC time once when the system boots
      - pcf8563.read_time: my_time
      - light.turn_on: backlight
      - text_sensor.template.publish:
          id: rtc_template_sensor
          state: !lambda |-
            char str[17];
            time_t currTime = id(my_time).now().timestamp;
            strftime(str, sizeof(str), "%Y-%M-%d %H:%M", localtime(&currTime));
            return  { str };
      - display.page.show: $default_page

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  # level: DEBUG

api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$room Dial"
    password: !secret fallback_password

captive_portal:

i2c:
  - id: bus_internal
    sda: GPIO11
    scl: GPIO12
    scan: False

touchscreen:
  platform: ft5x06
  address: 0x38

time:
  - platform: pcf8563
    id: my_time
    address: 0x51
    update_interval: never
  - platform: homeassistant
    on_time_sync:
      then:
        - pcf8563.write_time: my_time
        - text_sensor.template.publish:
            id: rtc_template_sensor
            state: !lambda |-
              char str[17];
              time_t currTime = id(my_time).now().timestamp;
              strftime(str, sizeof(str), "%Y-%m-%d %H:%M", localtime(&currTime));
              return  { str };

display:
  - platform: ili9xxx
    model: gc9a01a
    reset_pin: GPIO8
    id: dial_display
    cs_pin: GPIO7
    dc_pin: GPIO4
    dimensions: 
      height: 240
      width: 240

rc522_i2c:
  i2c_id: bus_internal
  address: 0x28
  on_tag:
    then:
      - rtttl.play: "success:d=24,o=5,b=100:c,g,b"
      - homeassistant.tag_scanned: !lambda "return x;"

rtttl:
  output: my_speaker_output
  id: my_rtttl

uart:
  tx_pin: GPIO2
  rx_pin: GPIO1
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

spi:
  mosi_pin: GPIO5
  clk_pin: GPIO6

number:
  - platform: template
    id: pi
    internal: true
    optimistic: true
    min_value: 3.14159265359
    max_value: 3.14159265360
    step: 0.00000000001
    initial_value: 3.14159265359

binary_sensor:
  - platform: gpio
    pin: GPIO42
    name: "$room Bezel Button"
    on_press:
      - if:
          condition:
            display.is_displaying_page: $default_page
          then:
            - display.page.show: $secondary_page
          else:
            - display.page.show: $default_page

light:
  - platform: monochromatic
    id: backlight
    name: "$room Backlight"
    output: oledbacklight
    default_transition_length: 250ms

output:
  - id: oledbacklight
    platform: ledc
    pin: GPIO9
    max_power: 1
    min_power: 0
  - platform: ledc
    pin: GPIO3
    id: my_speaker_output

text_sensor:
  - platform: template
    name: "$room RTC Sensor"
    id: rtc_template_sensor
  - platform: wifi_info
    ip_address:
      name: $room ESP IP Address
      id: espip
