sensor:
  - platform: homeassistant
    entity_id: sensor.mi_body_composition_scale_61dc_mass
    id: scale_current_weight
    filters:
      - multiply: 2.204623
      - round: 1
    on_value:
      - display.page.show: ScalePage
      - component.update: my_lcd
