binary_sensor:
  - platform: touchscreen
    name: "$room Weather Touch"
    x_min: 20 # Center x - radius
    x_max: 220 # Center x + radius
    y_min: 20 # Center y - radius
    y_max: 220 # Center y + radius
    page_id: WeatherPage
    on_press:
      # If weather page isn't default, tap to show default, otherwise show secondary.
      - if:
          condition:
            display.is_displaying_page: $default_page
          then:
            - display.page.show: $secondary_page
          else:
            - display.page.show: $default_page

display:
  - id: !extend dial_display
    pages:
      - <<: !include pages/weather_page.yaml

image:
  - id: weather_umbrella
    file: mdi:umbrella
    resize: 40x40
  - id: weather_clear_night
    file: mdi:weather-night
    resize: 110x110
  - id: weather_cloudy
    file: mdi:weather-cloudy
    resize: 110x110
  - id: weather_fog
    file: mdi:weather-fog
    resize: 110x110
  - id: weather_hail
    file: mdi:weather-hail
    resize: 110x110
  - id: weather_lightning
    file: mdi:weather-lightning
    resize: 110x110
  - id: weather_lightning_rainy
    file: mdi:weather-lightning-rainy
    resize: 110x110
  - id: weather_partlycloudy
    file: mdi:weather-partly-cloudy
    resize: 110x110
  - id: weather_pouring
    file: mdi:weather-pouring
    resize: 110x110
  - id: weather_rainy
    file: mdi:weather-rainy
    resize: 110x110
  - id: weather_snowy
    file: mdi:weather-snowy
    resize: 110x110
  - id: weather_snowy_rainy
    file: mdi:weather-snowy-rainy
    resize: 110x110
  - id: weather_sunny
    file: mdi:weather-sunny
    resize: 110x110
  - id: weather_windy
    file: mdi:weather-windy
    resize: 110x110
  - id: weather_windy_variant
    file: mdi:weather-windy-variant
    resize: 110x110
  - id: weather_exceptional
    file: mdi:alert
    resize: 81x801

sensor:
  - platform: homeassistant
    name: "weather_temperature"
    id: "weather_temperature"
    entity_id: weather.pirateweather
    attribute: temperature
    internal: true
    on_value:
      - component.update: dial_display

  - platform: homeassistant
    name: "Forecast Temp"
    id: "forecast_temperature"
    entity_id: sensor.weather_forecast_daily
    internal: true
    attribute: temperature
    on_value:
      - component.update: dial_display
  - platform: homeassistant
    name: "Forecast Temp Low"
    id: "forecast_temperature_low"
    attribute: templow
    entity_id: sensor.weather_forecast_daily
    internal: true
    on_value:
      - component.update: dial_display
  - platform: homeassistant
    id: "forecast_precip"
    name: "forecast_precip"
    entity_id: sensor.weather_forecast_daily
    internal: true
    attribute: precipitation_probability

text_sensor:
  - platform: homeassistant
    name: "weather_state"
    id: "weather_state"
    entity_id: $weather_entity
    internal: true
    on_value:
      - component.update: dial_display
